### ISSUE TITLE
Prepare Core 3.0 PSD 04

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#234]

**Comment by jamsden** [comment]
See [How to publish a spec](https://github.com/oslc-op/oslc-specs/wiki/How-to)

Publication checklist:

- [ ] base URI updated
- [ ] `specStatus` updated
- [ ] `publishDate` set
- [ ] `latestVersion` updated to point to the one for the OP, not the TC (only for the first PSD)
- [ ] open-services.net redirects resolve to the current published specs/drafts
- [ ] `additionalArtifacts` links are relative
- [ ] no broken links other than the stage-to-be-published
- [ ] [release draft](https://github.com/oslc-op/oslc-specs/releases/tag/untagged-40b8102c05f3fa132447) created
- [ ] [release zip](https://github.com/oslc-op/oslc-specs/releases/download/untagged-40b8102c05f3fa132447/rm-2.1-psd02_20190909.zip) uploaded
- [ ] PGB vote initiated (Sep 10)
- [ ] PGB vote secured
- [ ] OASIS review initiated (Sep 7)
- [ ] OASIS review passed
- [ ] OASIS archive uploaded

Some additional things to check that were issues in other specs:
- [ ] **OASIS:** in "Notices", the copyright year is missing - between "OASIS Open" and the period
- [ ] **OASIS:** the links to the "Previous stage" should use http instead of https in this case, since the earlier files were installed with http links. When the HTML is retrieved using https, it is unable to load the associated .css file, so the document is poorly presented.
- [ ] **OASIS:** add HTTPS to the image references


After the publication:
- [ ] update the https://open-services.net/spec/core/latest to point to https://docs.oasis-open-projects.org/oslc-op/core/v3.0/oslc-core.html
- [ ] open-services.net blog announcement

**Comment by berezovskyi** [comment]
@jamsden I don't think the PGB vote has been initiated yet

**Comment by berezovskyi** [comment]
@jamsden today you notified PGB but did not initiate a vote yet. I think you target to initiate a vote on Dec 13 and target to secure it on Dec 20.
