### ISSUE TITLE
Review Core 3.0 plan

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#244]
https://archive.open-services.net/wiki/core/Core-V3-Plan/index.html

**Comment by jamsden** [comment]
This is the original plan for OSLC 3.0 when the migration from open-services.net to OASIS was being considered. This is mostly either completed, or is out of date. The developers of this plan did not consider compatibility with OSLC 2.0. It turned out that the OSLC community tolerated API breaking changes when moving from OSLC 1.0 to 2.0, but it has been difficult to establish a viable business case for another API breaking release - especially for an integration technology that is already widely implemented. 

At this point, I think we're on track for OSLC 3.0 and need to get the 3.0 specifications that have been stable for a number of years published as OASIS Standards.
