### ISSUE TITLE
QM spec lists nonexistent properties in the Appendix re: compatibility

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#250]

**Comment by berezovskyi** [comment]
These are all CM properties. We shall replace the appendix with a link to the CM app.

**Comment by jamsden** [comment]
It's ok for the QM spec to reference related properties in other specifications, especially related properties that have become deprecated. In this case, "related" means a QM resource is the object of a CM assertion. But since this deprecation was done in 2.0, its not clear this needs to be highlighted in the 2.1 specifications. A simple note and reference to CM 3.0 is probably sufficient.
