### ISSUE TITLE
Why version compat in core is informative

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#255]
I would expect https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility to be normative.

**Comment by ndjc** [comment]
I think it's the same issue as you have recently fixed elsewhere - the intro paragraph(s) are intended to be the informative part, not the entire top-level section. Should be fixed by adding a new subsection as you did in those other cases.

**Comment by berezovskyi** [comment]
@ndjc something looks wrong there. There are no subsections. e.g. in §4 yes, the bug is clear and a subsection shall be inserted between §4 and §4.1.

@jamsden please check this.

**Comment by berezovskyi** [comment]
> Regarding version compatibility, there is nothing normative in that section for server implementations.

I would like to bring the version header and also have normative explanation of how servers and clients should send/interpret the header. I also don't think normative content is in any way limited to OSLC servers.

**Comment by jamsden** [comment]
Leaving this open after publishing PSD04 in case we decide to revisit the OSLC-Core-Version header.

**Comment by jamsden** [comment]
I'm assuming this doesn't need to be resolved for Core PS01.

**Comment by berezovskyi** [comment]
I am OK with postponing this but Chet said he will not allow any material changes after PS. In other words, if we with to change this after PS01 is approved and when submitting it for COS01, Chet will force us to make it PS02. Please decide yourself.

**Comment by jamsden** [comment]
Given the role OSLC plays as an integration framework, it is extremely important that all evolution of OSLC be backward compatible. We insist on this in the specifications for vocabulary, and should do the same for the REST API.

OSLC 1.0, OSLC 2.0 and the original OSLC 3.0 were all completely incompatible in both REST API and resource content. We pulled back on this for OSLC 3.0 to make it compatible with OSLC 2.0. You don't get three incompatible chances for an integration framework without making it irrelevant.

In addition, the OSLC community and marketplace has evolved, matured and centered around OSLC 2.0. As a practical business matter, the existing OSLC 2.0 implementations are not likely to change, especially just to exploit LDP and link headers. OSLC 2.0 already solves the integration problems and there's enough existing adoption to achieve momentum. OSLC integrations are still being implemented, and OSLC 2.0 APIs such as eclipse/Lyo, Lyo/Designer MDA, etc. all use OSLC 2.0.

We have to keep the OSLC-Core-Version header because of the incompatibility between OSLC 1.0 and 2.0, and there are still implementations of OSLC 1.0 (although the are slowly disappearing). 

But we do not need to add a 3.0 value for this header to distinguish 3.0 capabilities. Everything is directly introspected and discoverable from the REST API.

Future extensions to OSLC should maintain the REST API and vocabulary backwards capability in order for OSLC to meet its original intent. 

So I think this can be closed, no action.

**Comment by berezovskyi** [comment]
Jim, I think I can agree with using "OSLC-Core-Version: 2.0" for OSLC 3.0 servers. However, the main focus of this ticket is to make the section normative. The section contains statements on version header and precedence of Turtle over HTML and we must stand by it.

I think we just need to remove the line _This section is non-normative._ from Section 5 to resolve this ticket.

**Comment by jamsden** [comment]
This is non-normative because it has no conformance clauses, and has no impact on server implementations. Rather this is guidance for clients and for us as OSLC specification developers.

I suggest close, no change.

**Comment by berezovskyi** [comment]
Let's reword to have some conformance clauses then:

1. OSLC Core 3.0 implementations SHALL utilize an `OSLC-Core-Version: 2.0` header.
2. In this specification, machine-readable content SHALL have precedence over the normative specification if any discrepancies or errors arise.

**Comment by berezovskyi** [comment]
Agreed to make parts normative, see #475 for the work progress
