### ISSUE TITLE
ReSpec generating to many <hr>s

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-specs#319]
See resource-shape.html, right before section 5. There are three <hr>s generated when there should only be one.

**Comment by ndjc** [comment]
The problem is the two <h3> paras you have under the section for section 5. ReSpec expects only a single header per top sections, and you have the <h2> header at the beginning of the section shape-resource-shapes, plus those two <h3> headers. Since they are not in a div or section of their own, ReSpec resets the header level to <h2>, and then puts out an <hr> at the end of the previous section for each one of those now-<h2> headers.

To fix this, you need to avoid having more than one header at the top level of each top section. Either add more sections, or more divs, or avoid using <h1>, <h2>, <h3>, ... tags for the items.

**Comment by jamsden** [comment]
Fixed, I could just move the <h3> elements inside the following <div>.
