### ISSUE TITLE
Shall we publish a different HTML page for the vocabs?

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#327]
Do we need to generate an analogue of the XSLT-produced page for conneg when text/html or no specific content type is requested? Our agreement was no, but I am opening this to let @ndjc to comment in case we missed something.

**Comment by jamsden** [comment]
I say no, especially since we could redirect to specific sections in the vocab.html docs. I'd rather reduce the redundancy, the number of things we have to generate, the number of tools we have to support, scripts we have to write, maintain, and use, and any confusion these different representations might cause for users. 

All these things add to the overhead of developing, publishing and maintaining the specs, and can become an inhibitor to contribution.

**Comment by ndjc** [comment]
I'm happy with any solution that means a browser can show an HTML version of the vocabulary when fed a URL such as http://open-services.net/ns/core. If that is done by redirecting to, or directly serving, a relevant anchor in the vocabulary as published in the rendered HTML, that's OK with me. (It does mean we have no easy way to serve a vocabulary page for a spec like config mgt where there is no published spec yet - but then that's just more incentive for me to get a first publishable draft ready!)

I would reject any solution where a browser would show RDF source (Turtle or any other format) in response to http://open-services.net/ns/core - that would be a regression from OSLC 2.

**Comment by berezovskyi** [comment]
Nick, do you agree with a redirect to a -vocab.html for each ns prefix or do you have something else in mind?

Cheers,
Andrew

________________________________

**Comment by berezovskyi** [comment]
The decision made today during the call is NO (for the new spec drafts).
