### ISSUE TITLE
ShapeChecker Ant file is incomplete

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#37]
https://github.com/oslc-op/oslc-specs/blob/master/tools/ShapeChecker/build.xml does not produce a working JAR

**Comment by ndjc** [comment]
It is incomplete rather than broken! I use Eclipse, and that does the compilation, so I only use the ant file to construct the jar file. I'll update the issue to reflect this.

But I agree the ant file should have compilation steps added. However, that is not as obvious to accomplish as it sounds, since ShapeChecker uses annotation processing - let's discuss in the next meeting.

**Comment by berezovskyi** [comment]
Ok, let's discuss tomorrow. I will try to migrate from ant to gradle tonight. We need to eliminate any GUI tools from the build path in order to automate the process.

--
/Andrew
(from phone)



On Wed, May 29, 2019 at 8:04 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


It is incomplete rather than broken! I use Eclipse, and that does the compilation, so I only use the ant file to construct the jar file. I'll update the issue to reflect this.

But I agree the ant file should have compilation steps added. However, that is not as obvious to accomplish as it sounds, since ShapeChecker uses annotation processing - let's discuss in the next meeting.

**Comment by berezovskyi** [comment]
There is a Gradle file now. No need to fix Ant file any more.
