### ISSUE TITLE
Part 8 §6 is missing conformance clause IDs

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#462]
https://oslc-op.github.io/oslc-specs/specs/core/core-shapes.html#h2_conformance does not have a proper conformance clause table with XYZ-### identifiers.

This does not allow to label test failures like `org.eclipse.lyo.testsuite.oslcv2.ServiceProviderCatalogXmlTests#serviceProviderCatalogsHaveAtMostOneTitle` with a code, e.g. `CORSH-1` for the

> OSLC servers MUST follow the constraints defined here where required, and with the meanings defined here.

**Comment by berezovskyi** [comment]
@ndjc could you please take a look and suggest how to proceed?

**Comment by berezovskyi** [comment]
Please assign me back once you have a proposal.

**Comment by ndjc** [comment]
There is no table in section 6 because the spec author requested it be left out by setting 

> noConformanceTable: true,

in the config section.

There are no conformance clauses marked because the spec author has not tagged any paragraphs, spans, etc., with the

> class='conformance'

marker.

There is also some body text marked with the HTML tag

> \<h2 class="normalText"\>

This is unnecessary and confusing - why is not such text just tagged \<p\> ... \</p\>?

**Comment by jamsden** [comment]
I didn't put conformance clauses in any vocab or shape document.

**Comment by berezovskyi** [comment]
Thanks, Nick!

1. I will bring the table back if needed, thank you.
2. I will insert quite a few clauses, I expect it to be similar to the changes I had to do in RM Shapes COS draft part.
3. I will fix the normaltext header in the same PR.

> I didn't put conformance clauses in any vocab or shape document.

Jim, I did that. We cannot have text like "SHOULD be x" in a non-normative section without marking it with a conformance clause and marking the section normative.

**Comment by berezovskyi** [comment]
As you can guess, there are plenty of normative statements I could mark. 5 warnings removed, 17 to go:
 
![image](https://user-images.githubusercontent.com/64734/107270405-30dfd900-6a4b-11eb-86e1-16708b98896e.png)

**Comment by jamsden** [comment]
> Thanks, Nick!
> 
> 1. I will bring the table back if needed, thank you.
> 2. I will insert quite a few clauses, I expect it to be similar to the changes I had to do in RM Shapes COS draft part.
> 3. I will fix the normaltext header in the same PR.
> 
> > I didn't put conformance clauses in any vocab or shape document.
> 
> Jim, I did that. We cannot have text like "SHOULD be x" in a non-normative section without marking it with a conformance clause and marking the section normative.

We added conformance clauses and tables as a convenience for OASIS, there is nothing formal about them. The normative sections of the documents apply regardless of these tables. 

I believe we agreed to not do this for vocab and shape documents because the are already organized into concise groupings/tables and adding conformance clauses would add a lot of noise and little value to these documents.
