### ISSUE TITLE
Support nested OSLC errors with cause

### ISSUE THREAD

**Issue by DavidJHoney** [oslc-op/oslc-specs#465]
In some cases, OSLC errors will be reported by an implementation from a Java exception. A Java exception can have nested causing exceptions. However, currently these cannot be represented as a nested series of OSLC errors.

Proposal: For the resource shape for `oslc:Error`, add an optional property as follows:

| Prefixed Name | Occurs | Read-only | Value-type | Representation | Range | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| `oslc:cause` | Zero-or-one | true | Resource | Inline | `oslc:Error` | The error that caused this error.  |

**Comment by berezovskyi** [comment]
Great initiative for nested error! I would suggest to use `Zero-or-many` cardinality to allow error reporting other than stacktraces. E.g. a certain 401 error may be caused by (a) lack of a given membership (b) admin restriction to enforce membership on a given area. I simply don't see a reason to restrict the cause to a single item from the start. Would you be able to make a PR, please? Merry Christmas and happy holidays!

**Comment by DavidJHoney** [comment]
If an operation fails for multiple reasons, then I think might want to consider whether an error response can/should contain multiple oslc:Error resources.

**Comment by berezovskyi** [comment]
Fair enough.

**Comment by berezovskyi** [comment]
@DavidJHoney please make a PR ASAP to wrap Core PS02 in two weeks.
