### ISSUE TITLE
Merge the content from the v2 spec into part 1 wrt versioning 

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#476]
We want to move https://archive.open-services.net/bin/view/Main/OslcCoreSpecification#Specification_Versioning to §4.2

Rationale:

- We want to avoid having people consult both versions of the same spec
- We want to make sure the whole text reached OS stage
- We want to avoid adding text that will inadvertently be incompatible with the v2 spec, should have it all in one place to scrutinize during public review
- We want to make some parts of the text in v2 and v3 normative as tracked in #475 

Approach will follow the agreement in https://github.com/oslc-op/oslc-admin/blob/master/minutes/2021/2021-02-04.md#iana-application, specifically §4.2.1 and §4.2.2 will be introduced.

**Comment by jamsden** [comment]
I'm ok with this, but we need to reach some stable document in order progress to OASIS Standard. So we need to be _**very**_ selective about making any more document changes.

**Comment by berezovskyi** [comment]
@ndjc @jamsden @DavidJHoney https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility ready for you to take a look at. Please check my comments in

**Comment by berezovskyi** [comment]
See https://github.com/oslc-op/oslc-specs/issues/128#issuecomment-777735563 regarding the MUST on the version header. Nick promised to write something about the original intent, I also reworded the "v3.0 not needed" statement into 

> OSLC Core 3.0 clients and servers may continue to utilize the OSLC-Core-Version header with the value of "2.0".

**Comment by DavidJHoney** [comment]
Comments on the draft at [https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility](https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility)

Re: 4.2.2 - "OSLC Core 3.0 does not introduce any changes that would break existing OSLC 2.0 clients. Because of this, OSLC Core 3.0 clients and servers MAY continue to utilize the OSLC-Core-Version header with the value of "2.0"."
As Jim pointed out, it does for discovery. An OSLC 3.0 server that only implemented discovery using link headers (and not with SPCs) would be unusable for an OSLC 2.0 client. With hindsight, and subsequent distancing from overuse of LPDCs, that was probably a mistake. Had the spec been worded to make SPCs recommended, and link headers an optional addition, this would have been a non-breaking change.

I think we need to clarify the purpose of the header in requests, and whether the header should be required or optional. Here are some use cases:

1.  If a server does not support Core 1.0, I think the specification should say that a request with `Oslc-Core-Version: 1.0` should be rejected with a 400 Bad Request response.
2. If a server provides different RDF data between an OSLC resource and a non-OSLC resource, it might require a `Oslc-Core-Version: 2.0` header. DOORS Next is an example of this use case.
3. If a server's response to a GET of a resource doesn't depend on a `Oslc-Core-Version` header, I think that header should be optional in requests.

I have concerns about the use of `Oslc-Core-Version` in responses. 

The current wording in 4.2.3 item 4 requires that a GET of an _OSLC Defined Resource_ **MUST** include that header. 
Which raises the question, what is an _OSLC Defined Resource_?
For example, a GET of a change request is likely to include `dcterms:creator` in the RDF representation. Is a GET on that creator URI required to include that header?
Since section 3.2 in [https://oslc-op.github.io/oslc-specs/specs/core/core-shapes.html](https://oslc-op.github.io/oslc-specs/specs/core/core-shapes.html) defines a `foaf:Person`, one might argue that the creator is an _OSLC Defined Resource_ and that the response to a GET **MUST** include that header. But what if the user is defined in some non-OSLC LDAP server?
Just because an OSLC specification defines a shape for a resource, does it require that all servers (OSLC or not) that provide resources of that type are bound by that requirement?
So I think we should use different wording, or define what we mean by _OSLC Define Resource_.

In many cases, the RDF representation of a resource is defined by an OSLC domain specification, such as Requirements Management, Quality Management, Change Management, not by OSLC Core. So it seems to me that an `Oslc-Core-Version` header cannot say anything useful about the RDF representation of a requirement, test case, or change request.
Say we broke our cardinal rule of making a breaking change in Change Management 3.0. It seems to me that using `Oslc-Core-Version`  to distinguish the RDF representation of a change request is wrong. We should use a different header, such as `Oslc-Change-Management-Version` for such a purpose.

So I think we should distinguish the response to GETs of **OSLC Core** resources (such as SPCs, SPs) from non-Core resources. If we really want to require that the response to a GET of a change request or requirement includes `Oslc-Core-Version`, I think we should state that the value should always be "2.0". 

Are there any use cases where a response should include `Oslc-Core-Version: 1.0` or `Oslc-Core-Version: 3.0`?

1. Consider a GET of an SPC from a 3.0 server with request header `Oslc-Core-Version: 1.0`. It makes sense to me that if the server supports Core 1.0, the response includes the header `Oslc-Core-Version: 1.0`. If the server does not support core 1.0, it should return 400 Bad Request.
2. Consider a GET of an SPC from a 3.0 server with request header `Oslc-Core-Version: 2.0`. It makes sense to me that if the server supports Core 2.0, the response includes the header `Oslc-Core-Version: 2.0`. If the server does not support core 1.0, it should return 400 Bad Request.
3. Consider a GET of an SPC from a 3.0 server with request header `Oslc-Core-Version: 3.0`. If the server supports Core 3.0, but the response is no different from core 2.0, should the response includes the header `Oslc-Core-Version: 2.0` or `Oslc-Core-Version: 3.0`? Our discussion suggested that the former was preferred. If the server does not support core 3.0, it should return 400 Bad Request.

Now that we've introduced "3.0" has a valid value for the header, I think the specification needs to define how this should be handled by a 2.0 server and a 3.0 server. Under what cases, if any, would a response say `Oslc-Core-Version: 3.0`?

**Comment by frejfrej** [comment]
[P01] Agreed: the header was required, so it if is to return, we should probably make it required again.
[P02] Agreed.

**Comment by berezovskyi** [comment]
thank you @DavidJHoney and @frejfrej for taking time to read the section and provide comments.

@frejfrej I have addressed all the comments we went over today.

@DavidJHoney, thank you let me go over you comments one by one.

> Had the spec been worded to make SPCs recommended, and link headers an optional addition, this would have been a non-breaking change.

Let's do this. We can open a new issue to track this. If someone is against a SHOULD or MUST on SPCs, convince me you can build a usable OSLC Server with SPCs.

> different RDF data between an OSLC resource and a non-OSLC resource

![image](https://user-images.githubusercontent.com/64734/109189965-e4a7cf00-7794-11eb-92e3-16a9e124fc9f.png)

Jackie Chan aside, how can an OSLC Core 2.0 response be RDF and non-OSLC?

cc @ndjc here as well.

> If a server's response to a GET of a resource doesn't depend on a Oslc-Core-Version header, I think that header should be optional in requests.

I touched on that today in the call. In general, implementers do not have a crystal ball to properly implement clauses predicated on server details that are intrinsic (eg server that supports XYZ) as opposed to something that is part of the server interface. Moreover, OSLC 2.0 spec defined that OSLC 1.0 servers and clients were not aware of this header altogether and the lack of the header was to be interpreted as a request for 1.0 content. In summary, I don't think the sentence I quoted can be put into the spec as 2 clauses that will not conflict with the 2.0 spec. Please see newly numbered clauses 43-51 or more narrowly 43, 44, 50, 52, 53 in the latest draft (I am pushing my changes straight to master for this purpose).

>  Which raises the question, what is an OSLC Defined Resource?

We missed your statement on DOORS RDF responses that are not OSLC resources and assumed that simply to be sloppy wording but I think OSLC 3.0 does not permit such responses and clause 44 is supposed to reflect that.

>  Just because an OSLC specification defines a shape for a resource, does it require that all servers (OSLC or not) that provide resources of that type are bound by that requirement?

OSLC specifications apply to all servers that wish to call themselves OSLC Servers. Everyone else is free to implement any part of the spec as they wish. 

> It seems to me that using Oslc-Core-Version to distinguish the RDF representation of a change request is wrong.

I don't disagree with this and do not exclude the possibility of adding other version headers for other things in the future. E.g. TRS.

> I think we should state that the value should always be "2.0".

I think this is wrong, we can only augment CORE-45 with another clause that states that a major version MUST be 2 or higher.

> I think the specification should say that a request with Oslc-Core-Version: 1.0 should be rejected with a 400 Bad Request response.

Yes, I just add that to the spec. It's very good to state that clearly. See clauses 46 and 47.

> Are there any use cases where a response should include Oslc-Core-Version: 1.0 or Oslc-Core-Version: 3.0?

I could imagine an OSLC server that does not have an SPC and mostly supports LDP parts would want to advertise itself as a 3.0 server. But as I said in the call, I don't want to shoot ourselves here and make forward statements that will need extensive revision in future specs. I was floating the idea to define a term (Nick suggested "post-1.0 OSLC" clients/servers) and use that term instead of saying if 2.0 or if 3.0. So, I don't want to exclude the 3.0 header just to have to fully revise this text later.

**Comment by berezovskyi** [comment]
@DavidJHoney @frejfrej @jamsden @ndjc please see the changes live at https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility

The diff is at https://github.com/oslc-op/oslc-specs/commit/aff4dbc54f3507586012c35f60295b74b9bde6ed

**Comment by berezovskyi** [comment]
Action points:

- [ ] Remove CORE-54
- [ ] Remove CORE-55
- [ ] Apply P-14
- [ ] Change CORE-49 to "If the OSLC-Core-Version header is present and indicates a specification version that the Server cannot support, the Server SHOULD respond with what it determines is the most compatible version that it can return**; however, the server MAY reject the request with 400 Bad Request.**"
- [ ] Potentially update "An OSLC Client MUST preserve any unknown property values between requests to the OSLC Services for all HTTP verbs except PATCH (in accordance with the LDP specification §4.3.1.11). [CORE-21]" to clarify that property values means unrecognized triples and also to ignore headers.
- [ ] Remove §4.2.3 or move to PN

**Comment by berezovskyi** [comment]
All changes are now visible under https://oslc-op.github.io/oslc-specs/specs/core/oslc-core.html#versionCompatibility

**Comment by ndjc** [comment]
I like it. Two minor points:
1. The terms 'major' and 'minor' version are used but not defined.
2. In the second text paragraph of section "4.2.2 Versioning support in clients and servers", there is a statement that use of "another minor version" should be rejected - other than what? Presumably this means "any minor version number other than 0"?

**Comment by berezovskyi** [comment]
Good catch! I actually felt bad about not defining major and minor better than this:

> The OSLC-Core-Version header consists of a major and minor version components and must conform to the following ABNF

Regarding point 2: I think we should scope it to a major version below 2. So, any version below 2.0 is fair game for a 400 error:

> An OSLC Server SHOULD reject a request with the "OSLC-Core-Version" header with a major version value below "2" with a response 400 Bad Request

**Comment by berezovskyi** [comment]
@ndjc changes pushed in https://github.com/oslc-op/oslc-specs/commit/e47d1a55017d8394d405076db1182b2167daf2ac

**Comment by berezovskyi** [comment]
All changes approved during the OP calls, closing.
