### ISSUE TITLE
Spec section naming

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#52]
RM has a section called "Vocabulary Terms and Constraints". Does is make sense to call it "RDF Vocabulary Terms and OSLC Shapes" or "Vocabulary Terms and Shapes" and only inside the paragraph explain that shapes define constraints. There is no mention of OSLC Shapes anywhere and it may be confusing.

Ref: https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-spec.html#termsAndConstraints

**Comment by ndjc** [comment]
I'd be in favor of a change like this. The term 'constraints' smacks of closed world thinking, and shapes often provide more recommendations than constraints. Of course, some constraints are present, such as when the cardinality for a property is exactly one, but most properties are more loose, and things like OSLC:range provide probabilities rather than constraints.

**Comment by jamsden** [comment]
I guess I would prefer to avoid shapes, because the are often confused with closed-world data structure definitions, rather than open world constraints applied to a vocabulary for a specific purpose in a specific context. 

I'd also prefer to not make unnecessary changes to documents that have already gone through public review, and are just being converted to OP specs.

**Comment by berezovskyi** [comment]
> I would prefer to avoid shapes, because the are often confused with closed-world data structure definitions

Hmm, https://raw.githack.com/oslc-op/oslc-specs/master/specs/core/resource-shape.html is all about "Resource Shape"s!

> I'd also prefer to not make unnecessary changes to documents that have already gone through public review

I don't see new spec releases which have been in the works for the last few years "just being converted to OP specs". If changes need to be done, I want to see them done. Not trying to argue that my change is worth it but just expressing my general viewpoint.

**Comment by berezovskyi** [comment]
@jadelkhoury I leave it up to you

**Comment by jamsden** [comment]
I would prefer to stick with the more generic "Vocabulary Terms and Constraints" and avoid RDF and (the redundant) OSLC names in the title. Vocabulary Terms has commonly understood meaning and ResourceShapes do indeed define constraints - regardless of how specific they might be.

**Comment by berezovskyi** [comment]
> ResourceShapes do indeed define constraints

😹 😹 😹 

> jamsden closed this 30 minutes ago

I will let @jadelkhoury decide on it when he is back from the summer vacation. I still think that the change proposed is very simple and makes total sense.

**Comment by jadelkhoury** [comment]
The Introduction of the Part2:Vocabulary states 
> This specification defines a _vocabulary and resource shapes_ for the OSLC Requirements Management resources. 
See http://docs.oasis-open.org/oslc-domains/oslc-rm/v2.1/cs01/part2-requirements-management-vocab/oslc-rm-v2.1-cs01-part2-requirements-management-vocab.html#introduction

So _if_ we are to change, I'd say "vocabulary and resource shapes". I'd also change the text in the body to also talk about "vocabulary and resource shapes" instead of "vocabulary terms and constraints". It only adds to confusion to choose different words when we mean the same things.

I am however in favour of just keeping such changes to a minimal. 
Note that the QM also uses "vocabulary terms and constraints". it will add to more confusion if different domains use different headings.

**Comment by berezovskyi** [comment]
Let's close it without action and move faster towards PS01

**Comment by ndjc** [comment]
Also, given that we've determined that in most cases we want to split the shapes and vocals into different document parts to solve the anchor issues, the topic of a combined section header is somewhat moot!

**Comment by jadelkhoury** [comment]
> Also, given that we've determined that in most cases we want to split the shapes and vocals into different document parts to solve the anchor issues, the topic of a combined section header is somewhat moot!

In future releases of the specs I hope. (I.e. not mow) right?

**Comment by ndjc** [comment]
@jadelkhoury - that depends on your spec. If you have the vocabulary and shapes in the same HTML part of the spec AND you have used the same anchors for both the vocabulary terms and the shapes or property definitions, then links in the browser may not go where you want, and yes you may need to change before publication. See issue #334.
