### ISSUE TITLE
RM vocabulary terms missing

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#53]
The following terms are present in the Lyo Domains Domain Spec and in the RM Shapes (didn't fully check) but are missing from the vocab section (https://raw.githack.com/oslc-op/oslc-specs/master/specs/rm/requirements-management-vocab.html#vocabulary-details):

- elaborates
- specifies
- decomposedBy
- decomposes
- constrainedBy
- constrains
- satisfies

See https://docs.google.com/spreadsheets/d/1qWTjvesn1TKyLaD6f_VHs6ndqzaL5ADP95oazOIED9E/edit?usp=sharing

**Comment by jamsden** [comment]
These raise a couple of interesting questions. 

1) decomposedBy/decomposes might be better covered something generic that could be included in core common vocab

2) many of the others are inverses: e.g., elaborates vs elaboratedBy. We probably shouldn't define both in the vocabulary and shapes as that could lead to redundant data, or confusion about relationship loops and invariants. 

When in doubt, probably the vocabulary should rule because that's what was used in OSLC 2.0 implementations, not the shapes. This should however be verified against the 2.0 specifications.

**Comment by ndjc** [comment]
The OSLC specs originally defined a bunch of link types in both directions - with a pair of predicates, one for each direction. We later realized that was a mistake, since it meant a user had to compose more complex queries to look for either predicate. So a bunch of the link predicates were deprecated. If the missing RM ones are in this category, they should probably still be defined in the vocabularies but marked with vs:term_status = "archaic", just as was done for CM.

**Comment by jamsden** [comment]
decomposes, satisfies and constrains were not in the RM 2.0 vocabulary, but were included in the RM 2.0 spec. This was likely an error in the vocabulary. For consistency, we should add satisfiedBy and constrainedBy to the RM 2.1 vocabulary and remove the satisfies and constrains shapes. Also add decomposedBy shape.

elaborates and specifies were defined in the RM 2.0 shapes, but only elaboratedBy and specifiedBy were defined in the vocabulary. We should remove these shapes to be consistent with the vocabulary and avoid the redundancy. We can assume these were errors in the RM 2.0 spec.

**Comment by berezovskyi** [comment]
> The OSLC specs originally defined a bunch of link types in both directions - with a pair of predicates, one for each direction.

I think it makes total sense and deserves a `decomposedBy owl:inverseOf decomposes` semantic clarification.

> So a bunch of the link predicates were deprecated.

Is there a list of deprecations? I think it should be clearly highlighed in the new spec version.

> If the missing RM ones are in this category, they should probably still be defined in the vocabularies but marked with vs:term_status = "archaic"

What is `vs:` namespace?

> For consistency, we should add satisfiedBy and constrainedBy to the RM 2.1 vocabulary and remove the satisfies and constrains shapes. Also add decomposedBy shape.

Why are we talking about the shapes here? These are plain RDF properties. I am missing something?

> We should remove these shapes to be consistent with the vocabulary and avoid the redundancy. We can assume these were errors in the RM 2.0 spec.

How can we assume they were errors? I think (a) people might have used them and (b) they are quite useful inverse properties (maybe domain & range are not exactly right but that only means we should remove them from the shapes but not the vocabulary). So, I don't think we can remove something that may be in active use.

**Comment by ndjc** [comment]
See https://archive.open-services.net/wiki/core/V2DuplicatePredicates/index.html for an old analysis of links and deprecation of inverse ones. The discussion about this would have been in old mailing list archives and wiki pages - do we still have access to any of that? It would be a pity if it had all been lost.

Note that rather than have two real predicates with owl:inverseOf links between them, OSLC chose to define one primary link direction, with the oslc:inverseLabel property defining the label to be used if the relationship was traversed in the opposite direction. This was considered preferable for queries and report builders in a non-inferencing setup.

The vs:term_status predicate is defined in http://www.w3.org/2003/06/sw-vocab-status/ns#, and it is used in several OSLC specs (including Core) to define archaic terms. We do not recommend use of the'unstable' or 'testing' values of this predicate, since we felt such terms should not be added to a proposed standard in the first place. The only other value is "stable", and we take that as the default.

**Comment by berezovskyi** [comment]
Thanks Nick!

The analysis is great, we should follow it! What is the suggestion for the deprecated predicates without any proposal? I did not see the motivation for their complete removal.

Nothing is lost on the mailing list side. Everything is preserved by OASIS. Please see https://markmail.org/search/?q=org.oasis-open.lists.oslc for a searchable archive over all of our mailing lists on OASIS or https://www.mail-archive.com/search?l=all&q=open-services.net for the lists hosted on open-services.net before OSLC moved under OASIS.

And thanks for the vs:term_status pointer! I see it never got finalised, did the community agree on something different or did it just fall through the cracks?

**Comment by berezovskyi** [comment]
P.S. I think we should add 'unstable' to everything in our specs until they become OASIS standards (except for the things already finalised in previous releases, i.e. consider OSLC Core 2.0 stable but everything in the EMS spec shall be considered unstable). My humble opinion, of course.

**Comment by berezovskyi** [comment]
> OSLC chose to define one primary link direction

I don't think it's going to work across OSLC domains because tool vendors would not like to be on the non-primary side. So, I think, tools in all domains should have an equal shot at defining links towards artifacts under other domains.

**Comment by ndjc** [comment]
re defining things as 'unstable' - I really do not believe that's a good idea. Our goal with vocabularies has always been to make them guaranteed upward compatible; we add terms, but we never remove old ones or make incompatible changes to the meanings of existing ones. We do not have version numbers in vocabulary URIs.
One reason for this is that once any RDF data is published somewhere in the world, someone might have started writing queries against that data, and it is impossible for OSLC to mandate changes to either that existing data or those existing queries.

**Comment by ndjc** [comment]
Note the the above is not necessarily true for shapes. Our recommended URIs for shapes do include versions, and we have made changes to shapes over time. Even then. our general compatibility rules for OSLC standards has kept shapes mostly (if not entirely) upwards compatible.

**Comment by ndjc** [comment]
>> OSLC chose to define one primary link direction

> I don't think it's going to work across OSLC domains because tool vendors would not like to be on the non-primary side.

But the link direction does not mandate which end stores the link - if either. The 'anyone can say anything about any resource' nature of RDF allows links to be asserted regardless of the owners of the tools in question. OSLC decided to recommend just one direction for the link to keep the data model simpler for those trying to query, and for those trying to POST or PUT changes.

It is also the case that truly instantiating links in both directions is extremely difficult, if not impossible, in a configuration-managed environment. If there are two separate sources of truth for the existence of links, and those two separate sources use different configurations which may or may not then be contributed to the same global configurations, inconsistent views is almost inevitably the result.

**Comment by ndjc** [comment]
> And thanks for the vs:term_status pointer! I see it never got finalised, did the community agree on something different or did it just fall through the cracks?

I think it just fell through the cracks - there is no replacement or other equivalent that I am aware of, and apparently no one was interested enough to make it more formal, but OSLC started using it quite a while ago.

**Comment by berezovskyi** [comment]
@jadelkhoury waiting for your decision here regarding what to do with lyo.domains DS and/or the RM spec.

@ndjc @jamsden this issue was open as part of the [contracted work on the OSLC RefImpl](https://docs.google.com/document/d/1C1Yqgwa6xHW-kVL61urwn6OOp2d1yP_faM7HLWrA_-E/edit?usp=sharing)

**Comment by berezovskyi** [comment]
Yes, consistency is a weak point of inverse links that can be produced either by an inferencing engine or programmatically by different tools. Don’t have a good answer for that.

Can we indicate a primary direction and only include those properties in the configuration?

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 12:42 AM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


OSLC chose to define one primary link direction

I don't think it's going to work across OSLC domains because tool vendors would not like to be on the non-primary side.

But the link direction does not mandate which end stores the link - if either. The 'anyone can say anything about any resource' nature of RDF allows links to be asserted regardless of the owners of the tools in question. OSLC decided to recommend just one direction for the link to keep the data model simpler for those trying to query, and for those trying to POST or PUT changes.

It is also the case that truly instantiating links in both directions is extremely difficult, if not impossible, in a configuration-managed environment. If there are two separate sources of truth for the existence of links, and those two separate sources use different configurations which may or may not then be contributed to the same global configurations, inconsistent views is almost inevitably the result.

**Comment by jadelkhoury** [comment]
> @jadelkhoury waiting for your decision here regarding what to do with lyo.domains DS and/or the RM spec.

I don't see the point of mixing these 2 things in this thread (1) lyo.domains/RefImpl (2) the RM spec.

We here discuss and decide how the RM specs 2.1 should look like.  The ReferenceImplementation will simply implement that.

But I thought we have already finalized 2.1. So, besides fixing some missing vocabularies, should we really be changing the specs?

**Comment by berezovskyi** [comment]
Should I delete all those properties from the lyo.domains then?

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 11:21 PM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jadelkhoury<https://github.com/jadelkhoury> waiting for your decision here regarding what to do with lyo.domains DS and/or the RM spec.

I don't see the point of mixing these 2 things in this thread (1) lyo.domains/RefImpl (2) the RM spec.

We here discuss and decide how the RM specs 2.1 should look like. The ReferenceImplementation will simply implement that.

But I thought we have already finalized 2.1. So, besides fixing some missing vocabularies, should we really be changing the specs?

**Comment by jadelkhoury** [comment]
> Should I delete all those properties from the lyo.domains then?

lyo.domain is currently some half-accurate version of 2.0. 
Let's simply update it to match whatever 2.1 currently says. Assuming this is the final version of 2.1 (http://docs.oasis-open.org/oslc-domains/oslc-rm/v2.1/csprd01/part2-requirements-management-vocab/oslc-rm-v2.1-csprd01-part2-requirements-management-vocab.html)

**Comment by jamsden** [comment]
As in https://github.com/oslc-op/oslc-specs/issues/53#issuecomment-502749666

**Comment by jadelkhoury** [comment]
It seems we differ in whether we are to use the vocab or shapes as our reference for consistency.

I assumed Shapes when I edited RM 2.1 from 2.0. This was my line of thinking:
* I can only see Shapes in the 2.0 version. There are no vocabulary: https://archive.open-services.net/wiki/requirements-management/OSLC-Requirements-Management-Specification-version-2.0/index.html 
* That's why I made sure (and I have just re-checked) that the Requirement shapes in 2.0 and 2.1 matches. My assumption is that the shapes are what define the specs. 

Concerning your suggestions in https://github.com/oslc-op/oslc-specs/issues/53#issuecomment-502749666:
* "remove the satisfies and constrains shapes" : Isn't it confusing to remove shapes from 2.1 if they existed in 2.0. Then we need to at least explain the logic behind that.
* "elaborates and specifies were defined in the RM 2.0 shapes... We should remove these shapes": That sounds really drastic. These seem quite fundamental to me. Are you sur?

To me, if a vocab term (such as oslc_rm:elaborates) is referred to in shape, but happens to be missing from the vocab part, that is a bug that can be simply remedied by adding the vocab term. This would be correcting both the 2.0 and 2.1 versions.

Why can't we simply add the vocabulary terms that are referred to from any of the shapes? namely:
* oslc_rm:constrainedBy
* oslc_rm:constrains
* oslc_rm:decomposedBy
* oslc_rm:decomposes
* oslc_rm:elaborates
* oslc_rm:satisfies
* oslc_rm:specifies

**Comment by jamsden** [comment]
The vocabularies are the normative specification of the domain classes and properties. Shapes don't define vocabulary terms, they constrain them for a purpose - in this case, OSLC integration.  The 2.0 specs did include the vocabularies, but the shapes were only captured in HTML tables and were never validated. 

Removing shapes that have no vocabulary terms isn't removing anything from the spec vocabulary, its just fixing an error in the spec. In this case, the properties being removed are redundant with other properties, informally representing possible inverses. Nick has explained well why including these properties creates more problems then it solves.

**Comment by ndjc** [comment]
My comments on this issue were generic, and not necessarily definitive for this particular set of properties; I was not involved in the original RM 1.0 and 2.0 spec development. In particular, removing both directions of a relationship (e.g., `constrainedBy` **and** `constrains`) would remove all support for a link type. I suggest we get an opinion on these properties from @img.

**Comment by jadelkhoury** [comment]
So my approach for migrating from 2.0 to 2.1 did not match with your ideas. I did indeed look at the shapes in the HTML tables, to do a final end-to-end validation. Where are the 2.0 vocabularies?

**Comment by jamsden** [comment]
The 2.0 vocabularies are on open-services.net/ns. But this have been moved to the *-vocab.ttl files in the oslc-op repo. These should be compatible, but might not be identical.

**Comment by jadelkhoury** [comment]
But from an end user perspective, open-services.net/ns, and internal ttl-files are not so relevant, when they are reading the html pages and comparing the difference between 2.1 & 2.0. That ought to be of most relevance, no? 
 
It’s good we are lifting the vocabs into the 2.1 specs. 
If we think shapes are secondary, then let’s make that clear in the specs.

**Comment by berezovskyi** [comment]
Discussion continued with Ian under https://github.com/oslc-op/oslc-specs/issues/86 and it was decided to bring the properties back.
