### ISSUE TITLE
what structure shall be used for the ems spec?

### ISSUE THREAD

**Issue by FabioRNT** [oslc-op/oslc-specs#54]
As we can see on (https://archive.open-services.net/wiki/estimation-and-measurement/Estimation-and-Measurement-Service-Version-1.0_-REST-API/index.html), there are four HTML documents representing the sections of the specification. To fit the OASIS format, I'll have to edit it into a spec document and a vocab document, as well as a shapes.ttl file to create the shapes table. Since the information is spread, I'll need to know which goes into the spec document and which goes to the vocab document.

**Comment by jamsden** [comment]
The vocabulary has already been migrated, but the shapes have not yet been created.

Its probably fine to use the same pattern we've used for the other domain specifications, one -spec.htm and one -vocab.html document. The sections in the 2.0 spec are relatively short and I don't see a lot of benefit of keeping them in multi-part OASIS specifications compared to the cost. 

Its less clear what to do with [Standard URIs](https://archive.open-services.net/wiki/estimation-and-measurement/EMS-1.0-REST-API-Standard-URIs/index.html). These could be enumeration types that could be included in the vocabulary document, move into a section in the -vocab.html document, or kept as a separate multi-part document.

**Comment by ndjc** [comment]
I agree with Jim on simplifying the structure.

Looking at the standard URIs section, most of them are truly part of the EMS vocabulary - either classes, properties, or enum values - so they should be in the vocab.ttl file, and hence visible in the rendered vocabulary HTML file. Any terms used but not in the EMS namespace should probably be referenced in some way. For example, the spec say that http://open-services.net/ns/ems/unit#Second is the "same as qudt-unit:SecondTime" - so we should add at least a dcterms:seeAlso referencing that qudt term, or even an owl:sameAs.

**Comment by berezovskyi** [comment]
I agree on the simplified structure and also suggest to move Standard URIs into the vocab.

> http://open-services.net/ns/ems/unit#Second is the "same as qudt-unit:SecondTime

I truly have no idea why should we introduce another property that is semantically equivalent to the one defined by NASA.

> owl:sameAs

I am in favour of using OWL (e.g. `owl:inverseOf` is a no-brainer to me) but not `owl:sameAs` due to a number of problems with it (see https://www.w3.org/2009/12/rdf-ws/papers/ws21 for more details on the topic).

**Comment by ndjc** [comment]
I agree with some of the concerns expressed about owl:sameAs expressed in that paper, but I do not believe they apply in this case. Since the spec introducing the OSLC term defines it in terms of the qudt term, it seems to me they are truly intended to be identical. I completely agree with the questioning of why on earth this was done in the first place - if they are the same, we should have just used the qudt vocabulary, just as we reuse dcterms, rdfs, foaf, and many other vocabularies.

However, we cannot easily do that retroactively. Since the EMS namespaces exist, and those terms are defined, it would be incompatible to remove them. We could of course deprecate them - that is, mark them as archaic.

The article also mentions the possible use of skos instead of sameAs. I do not see that as particularly useful in this case - especially since (as the article agreed) the semantics of skos are a bit subjective.

**Comment by berezovskyi** [comment]
The biggest problem with sameAs is that it increases reasoning complexity. We’d like to stay in a mode that scales well to billions of triples.

Again, unless I am missing something, EMS spec was never finalised. I don’t feel any obligation to respect any compatibility guarantees for a spec that was never finalised (even though we can, by following your advice).

--
/Andrew
(from phone)



On Mon, Jun 17, 2019 at 10:11 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree with some of the concerns expressed about owl:sameAs expressed in that paper, but I do not believe they apply in this case. Since the spec introducing the OSLC term defines it in terms of the qudt term, it seems to me they are truly intended to be identical. I completely agree with the questioning of why on earth this was done in the first place - if they are the same, we should have just used the qudt vocabulary, just as we reuse dcterms, rdfs, foaf, and many other vocabularies.

However, we cannot easily do that retroactively. Since the EMS namespaces exist, and those terms are defined, it would be incompatible to remove them. We could of course deprecate them - that is, mark them as archaic.

The article also mentions the possible use of skos instead of sameAs. I do not see that as particularly useful in this case - especially since (as the article agreed) the semantics of skos are a bit subjective.

**Comment by jamsden** [comment]
OSLC has purposefully been designed to not require or use any reasoner. This is in part because OWL reasoners and traditional structural models have somewhat conflicting views on the meaning of domain and range properties, but also to keep OSLC adapter implementations simple and broadly applicable on different data sources. 

EMS was [Approved by steering committee 2013-05-15](http://open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2), but this was never noted in the spec.
Performance Monitoring uses a subset of the EMS vocabulary. This was suppose to be addressed during finalization. Rainer doesn’t recall any discussion about overlap with Performance Monitoring.

oslc-op will likely not do much with EMS unless some new demand arises. That could happen due to new interest from IBM Maximo. But let's wait until someone wants to contribute.

**Comment by berezovskyi** [comment]
Good! We need to reflect the StC approval somewhere.

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 4:07 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


OSLC has purposefully been designed to not require or use any reasoner. This is in part because OWL reasoners and traditional structural models have somewhat conflicting views on the meaning of domain and range properties, but also to keep OSLC adapter implementations simple and broadly applicable on different data sources.

EMS was Approved by steering committee 2013-05-15<http://open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2>, but this was never noted in the spec.
Performance Monitoring uses a subset of the EMS vocabulary. This was suppose to be addressed during finalization. Rainer doesn’t recall any discussion about overlap with Performance Monitoring.

oslc-op will likely not do much with EMS unless some new demand arises. That could happen due to new interest from IBM Maximo. But let's wait until someone wants to contribute.

**Comment by jamsden** [comment]
https://github.com/oslc-op/oslc-specs/wiki/OSLC-Domains-Working-Documents

**Comment by berezovskyi** [comment]
Actually, can I get a link to the StC approved version, please? I want to post it under the Specs page.

--
–Andrew.

2019-06-18  kl. 16:09 skrev Andrii Berezovskyi <andriib@kth.se<mailto:andriib@kth.se>>:

Good! We need to reflect the StC approval somewhere.

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 4:07 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


OSLC has purposefully been designed to not require or use any reasoner. This is in part because OWL reasoners and traditional structural models have somewhat conflicting views on the meaning of domain and range properties, but also to keep OSLC adapter implementations simple and broadly applicable on different data sources.

EMS was Approved by steering committee 2013-05-15<http://open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2>, but this was never noted in the spec.
Performance Monitoring uses a subset of the EMS vocabulary. This was suppose to be addressed during finalization. Rainer doesn’t recall any discussion about overlap with Performance Monitoring.

oslc-op will likely not do much with EMS unless some new demand arises. That could happen due to new interest from IBM Maximo. But let's wait until someone wants to contribute.

**Comment by jamsden** [comment]
http://archive.open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2

**Comment by berezovskyi** [comment]
Thanks, I mean the exact version of EMS that has been accepted.

--
–Andrew.

2019-06-18  kl. 17:12 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


http://archive.open-services.net/wiki/steering-committee/Mailing-List-Voting-Records/#oslc-perfmon-v2

**Comment by berezovskyi** [comment]
please reopen if there is anything else here or open a new issue
