### ISSUE TITLE
CM Actions file should be linked or removed

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#96]
What is oslc-specs/specs/cm/change-mgt-actions.html doing in the repo?

**Comment by jamsden** [comment]
A long time ago we decided to essentially deprecate OSLC actions as there were no implementations and we weren't sure this was the right way to go. To preserve the work, we moved Actions to CM because RTC used something like an early version of Actions to manage work item state changes. We decided not to include that in the CM 3.0 spec, but retained the actions file in the repo for possible future use. See https://github.com/oslc-op/oslc-specs/wiki/Action-Notes and https://github.com/oslc-op/oslc-specs/wiki/Automation-Specification-Notes for more information.

**Comment by berezovskyi** [comment]
Thank you for the insight. Given that we are going to tag stages, I don’t want this file in the repo. We should delete it and one can still get it from the history.

**Comment by ndjc** [comment]
I don't understand the tag comment above - we know the tags apply to the whole repo and not to just the files in a particular revision of a particular spec.

If we think the presence of the actions file is confusing, we should just move it to a different directory or subdirectory. Deleting it makes it much harder for people to find - if they even remember that it used to be there. And "CM Actions" is a topic we should revisit in future spec work, since the current spec leaves no way for clients to transition change requests to new states.

**Comment by berezovskyi** [comment]
@ndjc how about moving it under notes?

**Comment by ndjc** [comment]
No objection to moving it somewhere, and I have no preference as to where to move it.

**Comment by berezovskyi** [comment]
I thought about making it a separate spec (inspired by #112) but then looked at it and realised it was just

> the OSLC-CM workgroup design for actions

So, I still think the most appropriate place for this short document now it notes.

**Comment by berezovskyi** [comment]
The proposal for CM Actions is moved to the https://github.com/oslc-op/oslc-specs/tree/cm-actions branch (the file is kept in the same folder).
